// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrk8Mb-ASPz6aeLlDQol00wXqZVo90zbE',
    appId: '1:840528986993:web:03095c1cb5200418a5ecd0',
    messagingSenderId: '840528986993',
    projectId: 'ts-fashion-app',
    authDomain: 'ts-fashion-app.firebaseapp.com',
    storageBucket: 'ts-fashion-app.appspot.com',
    measurementId: 'G-5TQXRQQLLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKEcWMFcNineMllkNV6gh2jTFy_2z8rH4',
    appId: '1:840528986993:android:e4aeaa17dd5b65bea5ecd0',
    messagingSenderId: '840528986993',
    projectId: 'ts-fashion-app',
    storageBucket: 'ts-fashion-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB84bSx1imr7d8tM8Usdq6AyPp11UgRJCM',
    appId: '1:840528986993:ios:431886e9eee19b2ea5ecd0',
    messagingSenderId: '840528986993',
    projectId: 'ts-fashion-app',
    storageBucket: 'ts-fashion-app.appspot.com',
    iosClientId:
        '840528986993-io3oleg7l7qcmafqds1kvrfer55f46s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pradyun',
  );
}
